#!/bin/bash
# Translates environment variables into bitaxepid.py command-line arguments and
# an optional generated YAML config, then starts the tuner.
set -euo pipefail

APP="${BITAXEPID_HOME:-/app}"
DATA="${BITAXEPID_DATA:-/data}"

# Any extra arguments passed to the container are forwarded verbatim (escape hatch).
EXTRA_ARGS=("$@")

is_true() {
  case "${1,,}" in 1|true|yes|on) return 0 ;; *) return 1 ;; esac
}

if [[ -z "${BITAXE_IP:-}" ]]; then
  echo "ERROR: BITAXE_IP is not set. Set it to the IP address of your Bitaxe miner." >&2
  exit 1
fi

# ---- Prepare the persistent data directory -------------------------------
# bitaxepid.py resolves <ASICModel>.yaml, pools.yaml, user.yaml, the CSV/JSON
# logs and bitaxepid_monitor.log relative to its working directory, so we run
# from /data (a volume) and link the read-only defaults into it.
mkdir -p "$DATA"
for f in "$APP"/BM*.yaml; do
  [[ -e "$DATA/$(basename "$f")" ]] || ln -sf "$f" "$DATA/$(basename "$f")"
done
for f in pools.yaml user.yaml; do
  [[ -e "$DATA/$f" ]] || cp "$APP/$f" "$DATA/$f"
done
cd "$DATA"

# ---- Generated config from BITAXEPID_CFG_* -------------------------------
# Every key of the ASIC YAML (TARGET_TEMP, HASHRATE_SETPOINT, PID_FREQ_KP,
# POWER_LIMIT, MIN_VOLTAGE, ...) can be overridden with BITAXEPID_CFG_<KEY>.
# They are written to a YAML file that is passed with --config.
GEN_CFG="$DATA/env_config.yaml"
CFG_LINES=()
while IFS='=' read -r name value; do
  key="${name#BITAXEPID_CFG_}"
  [[ -z "$key" ]] && continue
  CFG_LINES+=("$key: $value")
done < <(env | grep -E '^BITAXEPID_CFG_[A-Za-z0-9_]+=' | sort || true)

ARGS=(--ip "$BITAXE_IP")

if [[ ${#CFG_LINES[@]} -gt 0 ]]; then
  {
    echo "# Generated by entrypoint.sh from BITAXEPID_CFG_* environment variables"
    printf '%s\n' "${CFG_LINES[@]}"
  } > "$GEN_CFG"
  ARGS+=(--config "$GEN_CFG")
elif [[ -n "${BITAXEPID_CONFIG:-}" ]]; then
  ARGS+=(--config "$BITAXEPID_CONFIG")
fi

# ---- Direct command-line switches ----------------------------------------
# DISABLE_FASTEST_POOLS=true skips get_fastest_pools() latency measurement;
# in that case PRIMARY_STRATUM (env var below) must be set or the tuner will
# exit at startup. If BACKUP_STRATUM is not also set, the primary pool is
# reused as the backup so the tuner keeps running with a single pool.
[[ -n "${USER_FILE:-}" ]]             && ARGS+=(--user-file "$USER_FILE")
[[ -n "${POOLS_FILE:-}" ]]            && ARGS+=(--pools-file "$POOLS_FILE")
[[ -n "${PRIMARY_STRATUM:-}" ]]       && ARGS+=(--primary-stratum "$PRIMARY_STRATUM")
[[ -n "${BACKUP_STRATUM:-}" ]]        && ARGS+=(--backup-stratum "$BACKUP_STRATUM")
[[ -n "${STRATUM_USER:-}" ]]          && ARGS+=(--stratum-user "$STRATUM_USER")
[[ -n "${FALLBACK_STRATUM_USER:-}" ]] && ARGS+=(--fallback-stratum-user "$FALLBACK_STRATUM_USER")
[[ -n "${VOLTAGE:-}" ]]               && ARGS+=(--voltage "$VOLTAGE")
[[ -n "${FREQUENCY:-}" ]]             && ARGS+=(--frequency "$FREQUENCY")
[[ -n "${SAMPLE_INTERVAL:-}" ]]       && ARGS+=(--sample-interval "$SAMPLE_INTERVAL")
[[ -n "${LOGGING_LEVEL:-}" ]]         && ARGS+=(--logging-level "${LOGGING_LEVEL,,}")

# Containers usually have no TTY, so plain console logging is the default.
# Set LOG_TO_CONSOLE=false (and tty: true in compose) to get the rich TUI.
if is_true "${LOG_TO_CONSOLE:-true}"; then ARGS+=(--log-to-console); fi
if is_true "${SERVE_METRICS:-false}"; then ARGS+=(--serve-metrics); fi
if is_true "${DISABLE_FASTEST_POOLS:-false}"; then ARGS+=(--disable-fastest-pools); fi

echo "Starting bitaxepid.py ${ARGS[*]} ${EXTRA_ARGS[*]:-}"
exec python "$APP/bitaxepid.py" "${ARGS[@]}" "${EXTRA_ARGS[@]}"
